export const careerQuestions = [
  {
    id: "interests",
    question: "What do you enjoy doing the most?",
    category: "Interests",
    options: [
      { value: "science_experiments", label: "Doing science experiments and research" },
      { value: "helping_people", label: "Helping people and understanding their pain" },
      { value: "building_things", label: "Designing and building things" },
      { value: "creative_arts", label: "Doing drawing, painting, or creative work" },
      { value: "numbers_data", label: "Working with numbers, data, and patterns" },
      { value: "teaching_mentoring", label: "Teaching or guiding others" },
    ],
  },
  {
    id: "subjects",
    question: "What was your favorite subject in school?",
    category: "Academics",
    options: [
      { value: "biology_chemistry", label: "Biology / Chemistry" },
      { value: "physics_maths", label: "Physics / Mathematics" },
      { value: "computer_science", label: "Computer Science / IT" },
      { value: "arts_literature", label: "Arts / Literature / Languages" },
      { value: "economics_commerce", label: "Economics / Commerce / Business" },
      { value: "social_sciences", label: "Social Sciences / History / Geography" },
    ],
  },
  {
    id: "work_style",
    question: "How do you prefer to work?",
    category: "Work Style",
    options: [
      { value: "solo_focused", label: "Working alone with focus" },
      { value: "team_collaboration", label: "Collaborating with a team" },
      { value: "outdoors_fieldwork", label: "Working outdoors in the field" },
      { value: "office_desk", label: "Structured work in an office" },
      { value: "creative_freedom", label: "Working with creative freedom" },
      { value: "helping_directly", label: "Interacting directly with people" },
    ],
  },
  {
    id: "strength",
    question: "What is your biggest strength?",
    category: "Strengths",
    options: [
      { value: "problem_solving", label: "Solving difficult problems" },
      { value: "communication", label: "Communicating well with people" },
      { value: "creativity", label: "Thinking of new ideas and creative solutions" },
      { value: "leadership", label: "Leading and inspiring a team" },
      { value: "attention_detail", label: "Paying attention to details and accuracy" },
      { value: "empathy_care", label: "Understanding people's feelings and caring for them" },
    ],
  },
  {
    id: "goal",
    question: "What is your biggest goal in life?",
    category: "Goals",
    options: [
      { value: "save_lives", label: "Saving lives and keeping people healthy" },
      { value: "build_technology", label: "Building future-changing technology" },
      { value: "financial_success", label: "Earning a lot of money and staying financially secure" },
      { value: "social_impact", label: "Bringing positive change to society" },
      { value: "creative_legacy", label: "Building a lasting creative legacy" },
      { value: "explore_discover", label: "Exploring the world and making new discoveries" },
    ],
  },
  {
    id: "environment",
    question: "What kind of environment do you like to work in?",
    category: "Environment",
    options: [
      { value: "hospital_clinic", label: "Healthcare settings like a hospital or clinic" },
      { value: "tech_startup", label: "A fast-paced tech company or startup" },
      { value: "school_university", label: "A school, college, or educational institution" },
      { value: "creative_studio", label: "A creative studio or media company" },
      { value: "corporate_finance", label: "A corporate office or financial firm" },
      { value: "research_lab", label: "A research lab or scientific institute" },
    ],
  },
  {
    id: "challenge",
    question: "What kind of challenges excite you the most?",
    category: "Challenges",
    options: [
      { value: "medical_diagnosis", label: "Solving complex medical or scientific mysteries" },
      { value: "tech_problems", label: "Fixing technical bugs and engineering problems" },
      { value: "business_strategy", label: "Finding business strategies and market opportunities" },
      { value: "creative_brief", label: "Completing creative briefs and artistic projects" },
      { value: "social_issues", label: "Addressing social problems and community challenges" },
      { value: "data_analysis", label: "Extracting insights from large datasets" },
    ],
  },
  {
    id: "role_model",
    question: "Who among these people do you admire the most?",
    category: "Inspiration",
    options: [
      { value: "doctor_surgeon", label: "Doctors and surgeons who save lives" },
      { value: "tech_innovator", label: "Tech innovators like Elon Musk or Steve Jobs" },
      { value: "scientist", label: "Scientists like Einstein or Marie Curie" },
      { value: "artist_creator", label: "Artists, writers, or filmmakers" },
      { value: "entrepreneur", label: "Entrepreneurs and business leaders" },
      { value: "social_leader", label: "Social workers and community leaders" },
    ],
  },
];

